import "./globals.scss";
import React from "react";
import type { Metadata } from "next";
import Navbar from "@/components/navbar/NavBar";
import Footer from "@/components/footer/footer";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";
import Provider from "@/context/session";

export const metadata: Metadata = {
    title: "school_management_app",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={"min-h-screen"}>
                <ThemeProvider
                    enableSystem
                    attribute="class"
                    defaultTheme="system"
                    disableTransitionOnChange
                >
                    <Provider>
                        <Navbar />
                        {children}
                        <Toaster />
                        <Footer />
                    </Provider>
                </ThemeProvider>
            </body>
        </html>
    );
}
